baseURL = '/'
languageCode = 'en-us'
title = 'Hadron Linux by Kairos'
publishDir = 'public'


[params]
  author = 'Hadron Linux by Kairos'
  description = 'The foundational Linux distribution for the cloud and the edge'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

