---
name: 'build container images'

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  toolchain:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: |
            ghcr.io/${{ github.repository }}-toolchain
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: type=gha,scope=hadron/ci-image-main
          cache-to: type=gha,mode=max,scope=hadron/ci-image-${{ github.ref_name }}
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ttl.sh/hadron-toolchain:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: type=gha,scope=hadron/ci-image-main
  container:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - toolchain
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: type=gha,scope=hadron/ci-image-main
          cache-to: type=gha,mode=max,scope=hadron/ci-image-${{ github.ref_name }}
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ttl.sh/hadron:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: type=gha,scope=hadron/ci-image-main
      - name: Test container image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          target: container-test
          cache-from: type=gha,scope=hadron/ci-image-main
  hadron-bios:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: ["cloud", "default"]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: |
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-bios
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hadron/ci-image-main
          cache-to: type=gha,mode=max,scope=hadron/ci-image-${{ github.ref_name }}
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ttl.sh/hadron${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-bios:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hadron/ci-image-main
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
  hadron-trusted:
    runs-on: oracle-vm-32cpu-128gb-x86-64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud", "default" ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8d8c7c12f7b958582a5cb82ba16d5903cb27976a
        with:
          images: |
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hadron/ci-image-main
          cache-to: type=gha,mode=max,scope=hadron/ci-image-${{ github.ref_name }}
          build-args: |
            BOOTLOADER=systemd
            KERNEL_TYPE=${{ matrix.kernel }}
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ttl.sh/hadron-${{ matrix.kernel == 'cloud' && '-cloud' || '' }}-trusted:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hadron/ci-image-main
          build-args: |
            BOOTLOADER=systemd
            KERNEL_TYPE=${{ matrix.kernel }}
  build-kairos-bios:
    runs-on: ubuntu-latest
    needs:
      - hadron-bios
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.init
          push: true
          tags: ttl.sh/hadron-init-bios:${{ github.sha }}
          build-args: |
            BASE_IMAGE=ttl.sh/hadron-cloud-bios:${{ github.sha }}
            VERSION=v0.0.1-${{ github.sha }}
            TRUSTED_BOOT=false
  build-kairos-trusted:
    runs-on: ubuntu-latest
    needs:
      - hadron-trusted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.init
          push: true
          tags: ttl.sh/hadron-init-trusted:${{ github.sha }}
          build-args: |
            BASE_IMAGE=ttl.sh/hadron-cloud-trusted:${{ github.sha }}
            VERSION=v0.0.1-${{ github.sha }}
            TRUSTED_BOOT=true
  build-bios-iso:
    runs-on: ubuntu-latest
    needs:
      - build-kairos-bios
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build ISO
        run: |
          mkdir build
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/build/:/output \
          quay.io/kairos/auroraboot:v0.13.0 --debug build-iso --output /output/ \
          --override-name kairos-hadron-bios-${{ github.sha }} \
          docker:ttl.sh/hadron-init-bios:${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: kairos-hadron-bios-${{ github.sha }}.iso.zip
          path: build/*.iso
  build-trusted-iso:
    runs-on: ubuntu-latest
    needs:
      - build-kairos-trusted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build ISO
        run: |
          mkdir build
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/tests/assets/keys:/keys \
          -v $PWD/build/:/output \
          -v $PWD/tests/assets/sysext/:/overlay \
          quay.io/kairos/auroraboot:v0.14.0-beta1 --debug build-uki \
          --output-dir /output/ --public-keys /keys \
          --tpm-pcr-private-key /keys/tpm2-pcr-private.pem \
          --sb-key /keys/db.key \
          --sb-cert /keys/db.pem \
          --output-type iso \
          --overlay-iso /overlay \
          --sdboot-in-source \
          docker:ttl.sh/hadron-init-trusted:${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: kairos-hadron-trusted-${{ github.sha }}.iso.zip
          path: build/*.iso
  tests-bios:
    runs-on: fast # Custom runner, more memory and CPU
    name: ${{ matrix.test }} tests
    needs:
      - build-bios-iso
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        test:
          - "acceptance"
          - "reset"
          - "custom-partitioning"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        timeout-minutes: 5
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: kairos-hadron-bios-${{ github.sha }}.iso.zip
      - name: Enable KVM group perms
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-x86 qemu-system-x86 qemu-utils qemu-kvm acl udev mkisofs swtpm
          sudo setfacl -m u:runner:rwx /dev/kvm
      - name: Run tests
        env:
          USE_QEMU: true
          KVM: true
          MEMORY: 5000
          DRIVE_SIZE: 50000
          CREATE_VM: true
          CPUS: 4
        run: |
          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
          echo "ISO is: $ISO"
          cp tests/go.* .
          go mod download
          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        if: failure()
        with:
          name: acceptance-${{github.sha}}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
  tests-trusted:
    runs-on: fast # Custom runner, more memory and CPU
    name: ${{ matrix.test }} tests
    needs:
      - build-trusted-iso
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        test:
          - "acceptance-trusted-generic"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        timeout-minutes: 5
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: kairos-hadron-trusted-${{ github.sha }}.iso.zip
      - name: Enable KVM group perms
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-x86 qemu-system-x86 qemu-utils qemu-kvm acl udev mkisofs swtpm
          sudo setfacl -m u:runner:rwx /dev/kvm
      - name: Run tests
        env:
          USE_QEMU: true
          KVM: true
          MEMORY: 5000
          DRIVE_SIZE: 50000
          CREATE_VM: true
          CPUS: 4
          FIRMWARE: /usr/share/OVMF/OVMF_CODE.fd
          EMULATE_TPM: true
          UKI_TEST: true
        run: |
          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
          echo "ISO is: $ISO"
          cp tests/go.* .
          go mod download
          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        if: failure()
        with:
          name: acceptance-trusted-${{github.sha}}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn


